### ISSUE TITLE
Measuring color with a DOM element is slow.

### ISSUE THREAD

**Issue by trusktr** [bigtimebuddy/pixi-svg#1]
Consider using something like [`tinycolor`](https://www.npmjs.com/package/tinycolor2). I think that can be faster than [`measureColor`](https://github.com/bigtimebuddy/pixi-svg/blob/master/src/SVG.js#L88).

**Comment by bigtimebuddy** [comment]
Good suggestion :+1: Thanks

**Comment by bigtimebuddy** [comment]
Added a2a3cf9a7dca3a9de86836da2d2b1db536d494b6
