### ISSUE TITLE
Problem with path rendering 

### ISSUE THREAD

**Issue by rodighiero** [bigtimebuddy/pixi-svg#11]
Why I cannot render this element?

`<svg><path d="M476.98922567641745,249.94509216279818m0,13239.074933118814a13239.074933118814,13239.074933118814 0 1,1 0,-26478.14986623763a13239.074933118814,13239.074933118814 0 1,1 0,26478.14986623763z"></path></svg>`

I get this

`[PIXI.SVG] Draw command not supported: a `

**Comment by rodighiero** [comment]
I think it is because of the 'a'

**Comment by bigtimebuddy** [comment]
Yeah, arcs are not supported because of the difference between pixi and svg. I can take another look at this and see if there’s a solution.

**Comment by rodighiero** [comment]
Thank you!
