### ISSUE TITLE
cleaning issue with stage

### ISSUE THREAD

**Issue by rodighiero** [bigtimebuddy/pixi-svg#12]
Hi there again,

The reason why I am posting is that I am trying to move a data visualization created in d3 in PIXI. And it is complex as I using a cartographic projection.

I have a dumb issue with cleaning the screen. The previous rendering in PIXI was utterly cleaned, but here I have an overlapping with each cycle of drawing. May someone check if I am coding properly? Thanks, it is appreciated!

```js
const projection = d3.geoMercator()
const geoPath = d3.geoPath(projection)

export function drawLinks() {
    stage.clear()
    s.links.forEach(link => {
        const path = geoPath({
            type: "LineString",
            coordinates: [link.source.spherical, link.target.spherical]
        })

        let element = document.createElement('svg');
        element.innerHTML = '<path stroke="black" stroke-width=".1" fill='none' d='${path}' />'
        const svg = new SVG(element)

        stage.addChild(svg)

    })
}
```

**Comment by bigtimebuddy** [comment]
Do this instead of `stage.clear()`
```js
stage.removeChildren().forEach(child => child.destroy());
```

**Comment by rodighiero** [comment]
Thanks, it works perfectly!
