### ISSUE TITLE
No code after npm install

### ISSUE THREAD

**Issue by dontwork** [bigtimebuddy/pixi-svg#22]
Hi when i run `npm install pixi-svg --save` I can see the following in my node_modules directory. it contains no code

![image](https://user-images.githubusercontent.com/3646471/117941988-85247e80-b302-11eb-9d82-271d3d87d15f.png)

this is causing an error: `Module not found: Error: Can't resolve 'pixi-svg'...`

**Comment by bigtimebuddy** [comment]
Oops, looks like a bad publish. I published v2.3.1 which should be better :+1:
