### ISSUE TITLE
Arc paths don't draw correctly

### ISSUE THREAD

**Issue by Snowblaze** [bigtimebuddy/pixi-svg#33]
I am trying to check if the arc command is actually working as intended, but keep getting the module error.

Here is a code sandbox showing it.

https://codesandbox.io/s/pixijs-examples-events-hit-test-forked-yxtdjh

**Comment by bigtimebuddy** [comment]
Trying to get to the bottom of this. This is not specific to this package, but I have a hunch what might be going on here. Made a PR to pixijs to see if we can get it sorted.

**Comment by bigtimebuddy** [comment]
Is this working for you now?
https://codesandbox.io/s/pixijs-examples-events-hit-test-forked-h8eog8

Also, I found out that uBlock Chrome extension was creating issues on CodeSandbox, but disabling it helped.

**Comment by Snowblaze** [comment]
Yup, it surely does. But arc command doesn't, even though it's not the problem of this issue hehe

**Comment by bigtimebuddy** [comment]
Yeah, that seems like a bug. Thanks for reporting

**Comment by bigtimebuddy** [comment]
Updated the example above with v3.1.0. And it works :+1: 

![Screen Shot 2022-11-11 at 9 46 57 AM](https://user-images.githubusercontent.com/864393/201364054-4e69bbae-901a-402a-ac50-966330ccac36.png)

**Comment by Snowblaze** [comment]
Looks terrific!
