### ISSUE TITLE
Processing C command is wrong.

### ISSUE THREAD

**Issue by mladen107** [bigtimebuddy/pixi-svg#4]
https://github.com/bigtimebuddy/pixi-svg/blob/70fe6492078f49982c9d9d53bbce9f121d1d2b8a/src/SVG.js#L313

The correct implementation is:

```
 case 'C': {
                    this.bezierCurveTo(
                        command.cp1.x,
                        command.cp1.y,
                        command.cp2.x,
                        command.cp2.y,
                        x = command.end.x,
                        y = command.end.y
                    );
                    break;
                }
```

C is absolute (including control points)

Before fix:
![image](https://user-images.githubusercontent.com/8933347/31481941-24ed4972-af26-11e7-89ed-03a7ebadc408.png)
After fix:
![image](https://user-images.githubusercontent.com/8933347/31481988-6d81e896-af26-11e7-96d9-3b40d109f048.png)

**Comment by MxAshUp** [comment]
This also appears to be the case for Q and S.

**Comment by MxAshUp** [comment]
Opened a pull request here: https://github.com/bigtimebuddy/pixi-svg/pull/7

**Comment by bigtimebuddy** [comment]
Fixed.
